### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [2]:
import numpy as np

In [3]:
x=np.array([[3,2,np.nan,1],[10,12,10,9],[5,np.nan,1,np.nan]])

In [4]:
x

array([[ 3.,  2., nan,  1.],
       [10., 12., 10.,  9.],
       [ 5., nan,  1., nan]])

In [5]:
np.isnan(x)

array([[False, False,  True, False],
       [False, False, False, False],
       [False,  True, False,  True]])

##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [7]:
x1=np.arange(1,5).reshape(2,2)

In [8]:
x1

array([[1, 2],
       [3, 4]])

In [9]:
x2=np.array([[1,3],[2,4]])

In [10]:
x2

array([[1, 3],
       [2, 4]])

In [12]:
x1==x2

array([[ True,  True],
       [ True,  True]])

In [13]:
np.array_equal(x1,x2)

True

###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [5]:
x=np.arange(0,16).reshape(4,4)

In [6]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
x[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [5]:
x=np.array([1,2,3,4,5])

In [6]:
x

array([1, 2, 3, 4, 5])

In [7]:
type(x)

numpy.ndarray

In [8]:
y=np.array((1,2,3,4))

In [9]:
y

array([1, 2, 3, 4])

In [10]:
type(y)

numpy.ndarray

###### 5. Write a NumPy program to find common values between two arrays.

In [9]:
x1=np.array([1,2,3,4,5])

In [10]:
x1

array([1, 2, 3, 4, 5])

In [11]:
y1=np.array([1,8,3,7,5])

In [12]:
y1

array([1, 8, 3, 7, 5])

In [16]:
np.intersect1d(x1,y1)

array([1, 3, 5])

###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [7]:
x1=np.arange(1,7).reshape(3,2)

In [9]:
x1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
x1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [5]:
x=np.array([10,10,20,10,20,20,20,30,30,50,40,40])

In [6]:
x

array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])

In [7]:
np.unique(x,return_counts=True)

(array([10, 20, 30, 40, 50]), array([3, 4, 2, 2, 1], dtype=int64))

###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [19]:
x=np.array([[0,0,0],[1,2,3],[4,5,6]])

In [20]:
x

array([[0, 0, 0],
       [1, 2, 3],
       [4, 5, 6]])

In [21]:
y=np.array([10,11,12])

In [22]:
y

array([10, 11, 12])

In [23]:
np.add(x,y)

array([[10, 11, 12],
       [11, 13, 15],
       [14, 16, 18]])

###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [31]:
x=np.arange(0,16).reshape(4,4)

In [30]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
x[1]

array([4, 5, 6, 7])

###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [33]:
a=np.arange(0,16).reshape(4,4)

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
a[:2,2:4]

array([[2, 3],
       [6, 7]])

###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [4]:
import numpy as np
yesterday=np.datetime64("today","D")-np.timedelta64(1,"D")
print("yesterday:",yesterday)
today=np.datetime64("today","D")
print("today:",today)
tomorrow=np.datetime64("today","D")+np.timedelta64(1,"D")
print("Tomorrow:",tomorrow)

yesterday: 2022-10-29
today: 2022-10-30
Tomorrow: 2022-10-31


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [5]:
import datetime

In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
