### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [2]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [5]:
np.zeros(10,)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10,)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full((10,),5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [9]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [12]:
x=np.arange(10,51)

In [14]:
x[x%2==0]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

######4. Write a NumPy program to create a 3x3 identity matrix.

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### 5. Write a NumPy program to generate a random number between 0 and 1

In [18]:
np.random.random()

0.4185900327222829

###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [19]:
np.random.random(15,)

array([0.87652872, 0.20550339, 0.56813545, 0.86864883, 0.25980906,
       0.05194526, 0.92636929, 0.16785507, 0.83555107, 0.97658209,
       0.77108933, 0.19842867, 0.3620966 , 0.93266564, 0.29875158])

###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [3]:
a=np.arange(10,22).reshape(3,4)

In [6]:
a.flatten()
for i in a:
    print(i,end=" ")

[10 11 12 13] [14 15 16 17] [18 19 20 21] 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [27]:
x=np.array([1,8,3,5])

In [28]:
x

array([1, 8, 3, 5])

In [29]:
y=np.array([10,1,4,10])

In [30]:
y

array([10,  1,  4, 10])

In [31]:
np.multiply(x,y)

array([10,  8, 12, 50])

In [32]:
x*y

array([10,  8, 12, 50])

###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [34]:
w=np.arange(12,38)

In [35]:
w

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [36]:
w[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [37]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [39]:
x=np.arange(0,4).reshape(2,2)

In [40]:
x

array([[0, 1],
       [2, 3]])

In [41]:
np.sum(x)

6

In [42]:
np.sum(x,axis=0)

array([2, 4])

In [43]:
np.sum(x,axis=1)

array([1, 5])

###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [46]:
x1=np.array([4,5])

In [47]:
x1

array([4, 5])

In [50]:
x2=np.array([7,10])

In [51]:
x2

array([ 7, 10])

In [53]:
np.dot(x1,x2)

78